# Generated by Django 3.2 on 2021-05-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='first_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='last_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='password1',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='password2',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='password1',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='password2',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
