# Generated by Django 3.2 on 2021-05-29 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210529_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='password1',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='password2',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='password1',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='password2',
            new_name='username',
        ),
    ]
