# Generated by Django 3.2 on 2021-05-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='password1',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='password2',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
