# Generated by Django 3.2 on 2021-05-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210518_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, null=True)),
                ('last_name', models.CharField(max_length=128, null=True)),
                ('email', models.CharField(max_length=254, null=True)),
                ('password1', models.CharField(max_length=128, null=True)),
                ('password2', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
