# Generated by Django 3.2 on 2021-10-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHU', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='morbidityreport',
            name='totalcases',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
