# Generated by Django 3.2 on 2022-02-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHU', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalinfo',
            name='address',
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='barangay',
            field=models.CharField(blank=True, choices=[('', '------'), ('Aripdip', 'Aripdip'), ('Ilongbukid', 'Ilongbukid'), ('Poscolon', 'Poscolon'), ('San Florentino', 'San Florentino'), ('Calaigang', 'Calaigang'), ('San Dionisio', 'San Dionisio')], default=0, max_length=50),
        ),
    ]
