# Generated by Django 3.2 on 2022-02-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHU', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morbidityreport',
            name='barangay',
            field=models.CharField(blank=True, choices=[('Aripdip', 'Aripdip'), ('Ilongbukid', 'Ilongbukid'), ('Poscolon', 'Poscolon'), ('San Florentino', 'San Florentino'), ('Calaigang', 'Calaigang')], max_length=50),
        ),
    ]
