# Generated by Django 3.2 on 2021-06-14 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RHU', '0002_auto_20210612_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=300)),
                ('body', models.CharField(max_length=1000)),
                ('read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to='RHU.account')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to='RHU.account')),
            ],
        ),
    ]
