# Generated by Django 3.2 on 2022-03-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHU', '0002_auto_20220321_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Account'), (2, 'Patient'), (3, 'Admin'), (4, 'Time Slot'), (5, 'Appointment'), (6, 'Medical Test'), (7, 'Prescription'), (8, 'Admission'), (9, 'Medical Info'), (10, 'Message'), (11, 'Morbidity Report')], default=0),
        ),
    ]
