# Generated by Django 3.2 on 2021-12-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHU', '0002_morbidityreport_totalcases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
