# Generated by Django 3.2 on 2022-01-11 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RHU', '0003_alter_appointment_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalinfo',
            name='allergy',
        ),
        migrations.RemoveField(
            model_name='medicalinfo',
            name='alzheimer',
        ),
        migrations.RemoveField(
            model_name='medicalinfo',
            name='asthma',
        ),
        migrations.RemoveField(
            model_name='medicalinfo',
            name='diabetes',
        ),
        migrations.RemoveField(
            model_name='medicalinfo',
            name='stroke',
        ),
    ]
