# Generated by Django 3.2 on 2022-03-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHU', '0003_alter_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
