# Generated by Django 3.2 on 2022-03-21 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RHU', '0004_timeslot_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='date',
            new_name='slot_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appt_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slotdates', to='RHU.timeslot'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='RHU.timeslot'),
        ),
    ]
