# Generated by Django 3.2 on 2022-01-13 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RHU', '0004_auto_20220111_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinfo',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patiento', to=settings.AUTH_USER_MODEL),
        ),
    ]
