# Generated by Django 3.2 on 2022-03-27 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RHU', '0005_auto_20220321_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='slot_date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='medicalinfo',
            name='date',
        ),
    ]
