# Generated by Django 3.2 on 2022-03-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHU', '0006_auto_20220327_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appt_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='timeslot',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='endTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='startTime',
            field=models.TimeField(null=True),
        ),
    ]
