# Generated by Django 3.2.1 on 2022-03-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHU', '0006_auto_20220327_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appt_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='timeslot',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='endTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='startTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Account'), (2, 'Patient'), (3, 'Admin'), (4, 'Appointment'), (5, 'Medical Test'), (6, 'Prescription'), (7, 'Admission'), (8, 'Medical Info'), (9, 'Message'), (10, 'Morbidity Report')], default=0),
        ),
    ]
