# Generated by Django 3.2 on 2021-06-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHU', '0006_auto_20210615_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats', models.CharField(max_length=100)),
                ('freq', models.IntegerField(default=0)),
            ],
        ),
    ]
