# Generated by Django 3.2 on 2021-06-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHU', '0007_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorbidityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(blank=True, choices=[('Aripdip', 'Aripdip'), ('Ilongbukid', 'Ilongbukid'), ('Poscolon', 'Poscolon'), ('San Florentino', 'San Florentino'), ('San Andres', 'San Andres'), ('Calaigang', 'Calaigang'), ('San Dionisio', 'San Dionisio'), ('San Rafael', 'San Rafael')], max_length=50)),
                ('disease', models.CharField(blank=True, choices=[('URTI', 'URTI'), ('Pneumonia', 'Pneumonia'), ('Animal Bite', 'Animal Bite'), ('Fever with Unknown Origin', 'Fever with Unknown Origin'), ('Diarrhea', 'Diarrhea'), ('UTI', 'UTI'), ('Hypertension', 'Hypertension'), ('Diabetes', 'Diabetes'), ('Allergic cough', 'Allergic cough'), ('Skin disease', 'Skin disease'), ('Wound(all types)', 'Wound(all types)'), ('Emphysema', 'Emphysema'), ('Impetigo', 'Impetigo'), ('Allergic rhinitis', 'Allergic rhinitis')], max_length=50)),
            ],
        ),
    ]
