# Generated by Django 3.2 on 2021-06-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHU', '0008_morbidityreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Account'), (2, 'Patient'), (3, 'Admin'), (4, 'Appointment'), (5, 'Medical Test'), (6, 'Prescription'), (7, 'Admission'), (8, 'Medical Info'), (9, 'Message'), (10, 'Morbidity Report')], default=0),
        ),
    ]
