# Generated by Django 3.2 on 2021-06-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHU', '0010_morbidityreport_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='morbidityreport',
            name='classification',
            field=models.CharField(blank=True, choices=[('C', 'Communicable Disease'), ('NC', 'Non-communicable Disease')], max_length=10),
        ),
        migrations.AlterField(
            model_name='morbidityreport',
            name='disease',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
