# Generated by Django 3.2 on 2021-07-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHU', '0011_auto_20210629_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morbidityreport',
            name='classification',
            field=models.CharField(blank=True, choices=[('', '---------'), ('C', 'Communicable Disease'), ('NC', 'Non-communicable Disease')], max_length=10),
        ),
    ]
