# Generated by Django 3.2 on 2021-07-01 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RHU', '0012_alter_morbidityreport_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heatmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barangays', to='RHU.morbidityreport')),
                ('cases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbercases', to='RHU.morbidityreport')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='RHU.morbidityreport')),
            ],
        ),
    ]
