# Generated by Django 3.2 on 2021-07-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHU', '0013_heatmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='morbidityreport',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='morbidityreport',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Heatmap',
        ),
    ]
