# Generated by Django 3.2 on 2021-07-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHU', '0014_auto_20210704_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='morbidityreport',
            options={'verbose_name_plural': 'Morbidity Report'},
        ),
        migrations.AlterField(
            model_name='morbidityreport',
            name='classification',
            field=models.CharField(blank=True, choices=[('C', 'Communicable Disease'), ('NC', 'Non-communicable Disease')], max_length=10),
        ),
    ]
