# Generated by Django 3.2 on 2021-07-04 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RHU', '0015_auto_20210704_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalinfo',
            options={'verbose_name_plural': 'Medical Info'},
        ),
        migrations.AlterModelOptions(
            name='medicaltest',
            options={'verbose_name_plural': 'Medical Tests'},
        ),
        migrations.AlterModelOptions(
            name='statistics',
            options={'verbose_name_plural': 'Statistics'},
        ),
    ]
