# Generated by Django 3.2 on 2021-07-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHU', '0016_auto_20210704_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morbidityreport',
            name='cases',
            field=models.IntegerField(),
        ),
    ]
