# Generated by Django 3.2 on 2021-07-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RHU', '0019_alter_morbidityreport_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morbidityreport',
            name='barangay',
            field=models.CharField(blank=True, choices=[('Aripdip', 'Aripdip'), ('Ilongbukid', 'Ilongbukid'), ('Poscolon', 'Poscolon'), ('San Florentino', 'San Florentino'), ('Calaigang', 'Calaigang'), ('San Dionisio', 'San Dionisio')], max_length=50),
        ),
    ]
